# Generated by Django 6.0 on 2025-12-16 03:25

import django.core.validators
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_remove_user_confirmation_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким именем уже существует.'}, help_text='Обязательное поле. 150 символов.', max_length=150, unique=True, validators=[users.validators.validate_username_not_me, django.core.validators.RegexValidator(message='Недопустимые символы в имени пользователя', regex='^[\\w.@+-]+\\Z')]),
        ),
    ]
